Add Azure Pipelines CD pipeline (#67)

diff --git a/.azdo/build-container-template.yml b/.azdo/build-container-template.yml
--- a/.azdo/build-container-template.yml
+++ b/.azdo/build-container-template.yml
@@ -13,31 +13,44 @@ parameters:
     type: string
   - name: repository # name of container repository
     type: string
-  
+  - name: taskname # unique identifier for the task
+    type: string
+  - name: customArguments # custom arguments to acr az build
+    type: string
+    default: ''
+
+
 steps:
-- task: AzureCLI@1
-  displayName: Build and Push ${{ parameters.repository }}
-  inputs:
-    azureSubscription: $(AZURE_SUBSCRIPTION)
-    scriptLocation: inlineScript
-    inlineScript: |
-      set -euxo pipefail  # fail on error
-
-      # Generate an tag with a reproducible checksum of all files in $containerReferences by doing a checksum of all files
-      # in alphabetical order, then another checksum of their names and checksums.
-      # Running this command on windows-based infrastructure may return a different result due to CRLF
-      pushd ${{ parameters.sourceLocation }}
-      imageTag=$(find ${{ parameters.containerReferences }} -type f -exec md5sum {} \; | LC_COLLATE=C sort -k 2 | md5sum | cut -f1 -d ' ')
-      popd
-
-      # If the image with the generated tag doesn't already exist, build it.
-      if ! az acr repository show -n ${{ parameters.acr }} --image "${{ parameters.repository }}:$imageTag" -o table; then
-        echo No match found. Container will be built.
-        echo Tag for new container: $imageTag
-        az acr build \
-          -r ${{ parameters.acr }} \
-          -t "${{ parameters.repository }}:$imageTag" \
-          -t "${{ parameters.repository }}:latest" \
-          -f "${{ parameters.dockerFile }}" \
-          ${{ parameters.sourceLocation }}
-      fi
+  - task: AzureCLI@1
+    name: "${{ parameters.taskname }}"
+    displayName: Build and Push ${{ parameters.repository }}
+    inputs:
+      azureSubscription: $(AZURE_SUBSCRIPTION)
+      scriptLocation: inlineScript
+      inlineScript: |
+        set -euxo pipefail  # fail on error
+  
+        # Generate an tag with a reproducible checksum of all files in $containerReferences by doing a checksum of all files
+        # in alphabetical order, then another checksum of their names and checksums.
+        # Running this command on windows-based infrastructure may return a different result due to CRLF
+        pushd ${{ parameters.sourceLocation }}
+        imageTag=$(find ${{ parameters.containerReferences }} -type f -exec md5sum {} \; | LC_COLLATE=C sort -k 2 | md5sum | cut -f1 -d ' ')
+        popd
+  
+        # If the image with the generated tag doesn't already exist, build it.
+        if ! az acr repository show -n ${{ parameters.acr }} --image "${{ parameters.repository }}:$imageTag" -o table; then
+          echo No match found. Container will be built.
+          echo Tag for new container: $imageTag
+          az acr build \
+            -r ${{ parameters.acr }} \
+            -t "${{ parameters.repository }}:$imageTag" \
+            -t "${{ parameters.repository }}:latest" \
+            -f "${{ parameters.dockerFile }}" \
+            ${{ parameters.customArguments }} \
+            ${{ parameters.sourceLocation }}
+        else
+          echo "The existing image with tag "$imageTag" is found."
+        fi
+        set +x
+        echo "setting IMAGE_TAG output for task ${{ parameters.taskname }}"
+        echo "##vso[task.setvariable variable=IMAGE_TAG;isOutput=true]$imageTag"
